function elect = DB_GetElectrode(tank_id)
% elect = DB_GetElectrode(tank_id)



elect = mym([...
    'SELECT e.target,e.depth,e.tank_id, ', ...
    't.manufacturer,t.pid,t.product_id,t.map,t.col_space,t.row_space,t.site_area ', ...
    'FROM electrodes e ', ...
    'INNER JOIN db_util.electrode_types t ', ...
    'ON e.type = t.pid ', ...
    'WHERE e.tank_id = {Si}'],tank_id);

elect.map = str2num(char(elect.map));


