Description of subset
Home > OOP > @spikes > subset.m
subset
PURPOSE
Returns logical indexes in an array pointing to a subset of
SYNOPSIS
function ind = subset(obj,ids)
DESCRIPTION
 Returns logical indexes in an array pointing to a subset of
 data.
 Can enter one or multiple unit ids (in an array) or unit
 strings (in a cell array) which will search on unitstr field.
 Alternatively, the channel number and sortcode can be passed
 in as two parameters.  eg, ind = subset(3,2); would return
 logical indexing of unit 2 on channel 3.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plot_waveforms plot_waveforms(unitid)
spikes
unit_timestamps ts = unit_timestamps(obj,unitid)
SOURCE CODE
function ind = subset(obj,ids)
% Returns logical indexes in an array pointing to a subset of
% data.
%
% Can enter one or multiple unit ids (in an array) or unit
% strings (in a cell array) which will search on unitstr field.
%
% Alternatively, the channel number and sortcode can be passed
% in as two parameters.  eg, ind = subset(3,2); would return
% logical indexing of unit 2 on channel 3.
if ischar(ids), ids = cellstr(ids); end
if length(ids) == 1 && iscellstr(ids)
    ids = find(ismember(obj.unitstr,ids));
end
if length(ids) == 1
    ind = obj.units == ids(1);
elseif length(ids) == 2
    ind = obj.channels == ids(2) & obj.sortcode == ids(2);
end