Description of dbopen
Home > db > mym > dbopen.m
dbopen
PURPOSE
dbopen Make MySQL database current [mym utilities]
SYNOPSIS
function dbopen(name)
DESCRIPTION
 dbopen   Make MySQL database current    [mym utilities]
 Example  dbopen('new')
CROSS-REFERENCE INFORMATION
This function calls:
myisopen myisopen True if MySQL instance active [mym utilities]
mym MYM - Interact with a MySQL database server
This function is called by:
mydemo % MYDEMO: Demonstrate usage of mym utilities
SOURCE CODE
function dbopen(name)
% dbopen   Make MySQL database current    [mym utilities]
% Example  dbopen('new')
if ~myisopen
   error('No MySQL connection active; use ''myopen'' to connect')
else
   try
     a = mym(['use ' name]);   %#ok
   catch
     error('Database %s not found; use ''dblist'' to list available databases',name)
   end
end