Description of tbattr
Home > db > mym > tbattr.m
tbattr
PURPOSE
tbattr List columns of MySQL table [mym utilities]
SYNOPSIS
function[varargout] = tbattr(table)
DESCRIPTION
 tbattr   List columns of MySQL table    [mym utilities]
 Inputs   table - table name, string
 Outputs  names - column names, (m*1) cell array
          types - column types, (m*1) cell array (optional)
 Example  [names,types] = tbattr('project.orders')
CROSS-REFERENCE INFORMATION
This function calls:
istable istable True if MySQL table exists [mym utilities]
mym MYM - Interact with a MySQL database server
This function is called by:
mydemo % MYDEMO: Demonstrate usage of mym utilities
tbread tbread Read from MySQL table [mym utilities]
tbwrite tbwrite Write to MySQL table [mym utilities]
SOURCE CODE
function[varargout] = tbattr(table)
% tbattr   List columns of MySQL table    [mym utilities]
% Inputs   table - table name, string
% Outputs  names - column names, (m*1) cell array
%          types - column types, (m*1) cell array (optional)
% Example  [names,types] = tbattr('project.orders')
if ~istable(table)
   error('Table %s not found; use ''tblist'' to list available tables',table)
end
[a,b,c,d,e,f] = mym(['describe ' table]);    %#ok
varargout{1} = a;
if nargout == 2
   x = a;
   for k = 1:length(a)
       x{k} = char(cell2mat(b(k))');
   end
   varargout{2} = x;
end