Description of istable
Home > db > mym > istable.m
istable
PURPOSE
istable True if MySQL table exists [mym utilities]
SYNOPSIS
function[i] = istable(name)
DESCRIPTION
 istable  True if MySQL table exists     [mym utilities]
 Example  if istable('junk'), tbdrop('junk'), end
CROSS-REFERENCE INFORMATION
This function calls:
myisopen myisopen True if MySQL instance active [mym utilities]
This function is called by:
dblist dblist List MySQL databases [mym utilities]
tbadd tbadd Create MySQL table [mym utilities]
tbattr tbattr List columns of MySQL table [mym utilities]
tbprint tbprint List a few rows of MySQL table [mym utilities]
tbread tbread Read from MySQL table [mym utilities]
tbrename tbrename Rename MySQL table [mym utilities]
tbsize tbsize Size of MySQL table [mym utilities]
tbwrite tbwrite Write to MySQL table [mym utilities]
SOURCE CODE
function[i] = istable(name)
% istable  True if MySQL table exists     [mym utilities]
% Example  if istable('junk'), tbdrop('junk'), end
if ~myisopen
   error('No MySQL connection active; use ''myopen'' to connect')
else
   try
     i = false;
     [a,b,c,d,e,f] = myms(['describe ' name]);  %#ok
     i = true;
   catch
   end
end