Description of mydemo
Home > db > mym > mydemo.m
mydemo
PURPOSE
% MYDEMO: Demonstrate usage of mym utilities
SYNOPSIS
This is a script file.
DESCRIPTION
% MYDEMO: Demonstrate usage of mym utilities
 Example: mydemo (Oh, the FEX code metrics..)
CROSS-REFERENCE INFORMATION
This function calls:
dbadd dbadd Create MySQL database [mym utilities]
dbcurr dbcurr Current MySQL database [mym utilities]
dblist dblist List MySQL databases [mym utilities]
dbopen dbopen Make MySQL database current [mym utilities]
isdbase isdbase True if MySQL database exists [mym utilities]
myclose myclose Disconnect from MySQL [mym utilities]
myisopen myisopen True if MySQL instance active [mym utilities]
mym MYM - Interact with a MySQL database server
myopen myopen Connect to MySQL [mym utilities]
tbadd tbadd Create MySQL table [mym utilities]
tbattr tbattr List columns of MySQL table [mym utilities]
tblist tblist List tables of MySQL database [mym utilities]
tbread tbread Read from MySQL table [mym utilities]
tbsize tbsize Size of MySQL table [mym utilities]
tbwrite tbwrite Write to MySQL table [mym utilities]
This function is called by:
SOURCE CODE
%% MYDEMO: Demonstrate usage of mym utilities
% Example: mydemo (Oh, the FEX code metrics..)
%% List available functions
lookfor mym
%% Connect to MySQL
myisopen
myopen('localhost','root','fairfax')
myisopen
%% List available databases
dblist
%% Create database 'test2'
dbadd('test2')
%% Confirm that database 'test2' was created
isdbase('test2')
%% Make database 'test2' current
dbcurr
dbopen('test2')
dbcurr
%% Load FEX download data in file 'fex.txt' to table 'fex'
mym(['create table fex (' ...
     'time datetime, ' ...
     'id   mediumint unsigned, ' ...
     'rank smallint  unsigned, ' ...
     'file smallint  unsigned, ' ...
     'fcat tinyint   unsigned, ' ...
     'down smallint  unsigned)'])
tic
mym(['load data infile ''D:/Program Files/Matlab/work/fexstat/fex.txt'' ' ...
     'into table fex lines terminated by ''\n'' ' ...
     '(@time,id,rank,file,fcat,down) ' ...
     'set time = str_to_date(@time,''%d-%b-%Y %H:%i:%s'')'])
toc
%% List tables in database 'test2'
tblist
%% List names and types of 'fex' columns
[names, types] = tbattr('fex')
tbsize('fex')
%% Read contents of table 'fex' into Matlab workspace
who
tic
tbread('fex',names,names,'')
toc
who
%% Write loaded data back to MySQL (500 rows per pass), to a table that is a copy of 'fex'
tic
tbadd('fex2',names,types,'replace')
tbwrite('fex2',names,names,500)
toc
tbsize('fex2')
%% Disconnect from MySQL
myclose