Description of myisopen
Home > db > mym > myisopen.m
myisopen
PURPOSE
myisopen True if MySQL instance active [mym utilities]
SYNOPSIS
function[i] = myisopen
DESCRIPTION
 myisopen True if MySQL instance active  [mym utilities]
 Example  if mycheck, disp('MySQL running!'), end
CROSS-REFERENCE INFORMATION
This function calls:
mym MYM - Interact with a MySQL database server
This function is called by:
dbadd dbadd Create MySQL database [mym utilities]
dbcurr dbcurr Current MySQL database [mym utilities]
dbdrop dbdrop Delete MySQL database [mym utilities]
dblist dblist List MySQL databases [mym utilities]
dbopen dbopen Make MySQL database current [mym utilities]
isdbase isdbase True if MySQL database exists [mym utilities]
istable istable True if MySQL table exists [mym utilities]
mydemo % MYDEMO: Demonstrate usage of mym utilities
tbdrop tbdrop Delete MySQL table [mym utilities]
SOURCE CODE
function[i] = myisopen
% myisopen True if MySQL instance active  [mym utilities]
% Example  if mycheck, disp('MySQL running!'), end
i = ~mym('status');