Description of tblist
Home > db > mym > tblist.m
tblist
PURPOSE
tblist List tables of MySQL database [mym utilities]
SYNOPSIS
function[tables] = tblist(varargin)
DESCRIPTION
 tblist   List tables of MySQL database  [mym utilities]
 Inputs   name   - database name, string (optional, current database default)
 Outputs  tables - table names, (m*1) cell array
 Example  tblist('project')
CROSS-REFERENCE INFORMATION
This function calls:
dbcurr dbcurr Current MySQL database [mym utilities]
isdbase isdbase True if MySQL database exists [mym utilities]
mym MYM - Interact with a MySQL database server
This function is called by:
mydemo % MYDEMO: Demonstrate usage of mym utilities
SOURCE CODE
function[tables] = tblist(varargin)
% tblist   List tables of MySQL database  [mym utilities]
% Inputs   name   - database name, string (optional, current database default)
% Outputs  tables - table names, (m*1) cell array
% Example  tblist('project')
if nargin
   name = varargin{1};
   if ~isdbase(name)
      error('Database %s not found',name)
   end
else
   name = dbcurr;
   if isempty(name)
       error('No database selected; use ''dbopen'' to open a database')
   end
end
% new compilation of mym returns structure DJS 1/2013
t = mym(['show tables in ' name]);
fn = char(fieldnames(t));
tables = t.(fn);