function DB_CreateUnitPropertiesTable

mym(['CREATE TABLE IF NOT EXISTS db_util.analysis_params (', ...
     'id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT, ', ...
     'name VARCHAR(15) NOT NULL, ', ...
     'description VARCHAR(100) NULL, ', ...
     'ts DATETIME NULL DEFAULT CURRENT_TIMESTAMP, ', ...
     'PRIMARY KEY (id, name), ', ...
     'UNIQUE INDEX id_UNIQUE (id ASC), ', ...
     'UNIQUE INDEX name_UNIQUE (name ASC))']);

mym(['CREATE TABLE IF NOT EXISTS unit_properties ( ', ...
     'id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, ', ...
     'ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ', ...
     'unit_id INT UNSIGNED NOT NULL, ', ...
     'param_id SMALLINT UNSIGNED NOT NULL, ', ...
     'group_id VARCHAR(32), ', ...
     'paramS VARCHAR(256), ', ...
     'paramF FLOAT, ', ...
     'INDEX i_unit_prop_id (unit_id), ', ...
     'INDEX i_unit_prop_param (unit_id,param_id), ', ...
     'INDEX i_unit_prop_group_param (unit_id,group_id,param_id))']);
 
 try %#ok<TRYNC> 
     mym(['CREATE VIEW v_unit_props AS ', ...
          'select ', ...
            'a.name AS param,', ...
            'p.id AS id,', ...
            'p.ts AS ts,', ...
            'p.unit_id AS unit_id,', ...
            'p.param_id AS param_id,', ...
            'p.group_id AS group_id,', ...
            'p.paramS AS paramS,', ...
            'p.paramF AS paramF', ...
         'from (db_util.analysis_params a ', ...
            'join unit_properties p ', ...
            'ON ((a.id = p.param_id)))']);
 end
 
 






