Description of myms
Home > db > db_helpers > myms.m
myms
PURPOSE
varargout = myms(str)
SYNOPSIS
function varargout = myms(str)
DESCRIPTION
 varargout = myms(str)
 Wrapper function for mym.
 Returns individual outputs instead of a single structure.
 Use sprintf instead of normal mym inline placeholders like {Si}
 DJS 2013
 See also, sprintf, mym
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
DB_GetParams p = DB_GetParams(block_id)
DB_GetProtocolName pname = DB_GetProtocolName(protocol)
DB_UploadWaveData result = DB_UploadWaveData(tankname,blockname,eventname)
SOURCE CODE
function varargout = myms(str)
% varargout = myms(str)
%
% Wrapper function for mym.
%
% Returns individual outputs instead of a single structure.
%
% Use sprintf instead of normal mym inline placeholders like {Si}
%
% DJS 2013
%
% See also, sprintf, mym
varargout = struct2cell(mym(str));